#!/bin/bash
clear
#--------@NETCOLVIP----------#
source ShellBot.sh
touch lista
[[ -z $1 ]] && {
    clear && echo "INGRESE SU TOKEN" && return 0
}
[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✌️😃 Hola <b>${message_from_first_name[$id]}</b> Bienvenido(a) !\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="<b>GENERE SU TEST GRATUITO DE 4 HORAS!\n\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="<b>NETCOLVIP DANDO EL MEJOR SERVICIO</b>\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - Funcao pix
PIX() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="💠      ELIJA UNA CLAVE A CONTINUACIÓN.     💠\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="🔁                 CLAVE ALEATORIA                   🔁\n"
        msg+="🔑 ├ 7b04ueogt-2535-4777-aa5c-4ec751561c58\n"
        msg+="👤 ├ NETCOL VI0\n"
        msg+="💰 └ COP$ 5,000\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✅           CONFIRMAR FORMA DE PAGO          ✅\n"
        msg+="ENVÍE EL RECIBO P/ @NETCOLVIP\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="VERIFICACIÓN DE PAGO EN 24 HORAS\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - Funcao pix
pix() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="💠      ELIJA UNA CLAVE A CONTINUACIÓN.     💠\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="🔁                 CLAVE ALEATORIA                   🔁\n"
        msg+="🔑 ├ 7b04ueogt-2535-4777-aa5c-4ec751561c58\n"
        msg+="👤 ├ NETCOL VI0\n"
        msg+="💰 └ COP$ 5,000\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✅           CONFIRMAR PAGO           ✅\n"
        msg+="ENVÍE EL RECIBO P/ @NETCOLVIP\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="VERIFICACIÓN DE PAGO EN 24 HORAS\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "❌ Acceso denegado, verifique la hora de su última creación y regrese solo cuando complete 24 horas de su última creación."
      return 0
    }
    usuario=$(echo NETCOL$(( RANDOM% + 250 )))
    senha=$((RANDOM% + VIP999))
    limite='1'
    tempo='4'
    tuserdate=$(date '+%C%y/%m/%d' -d " +2 days")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
    chmod +x /etc/SSHPlus/userteste/$usuario.sh
    at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n        <b>✅ CREADO CON EXITO ✅</b>\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n            👤 USUARIO: <code>$usuario</code>\n               🔑 CLAVE: <code>$senha</code>\n             ⏰ VENCE EN: $tempo Horas")\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n  🌐 Dominios: \n Puerto 80: </code>f.cerebrocol.com</code>\n Puerto 443: </code>f.netcol.nl</code>\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n   ℹ️ COMO CONECTAR EL USUARIO\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n• Abra su app de preferencia HTTP CUSTOM.\n• La puedes descargar en las siguientes opciónes.\n• La app y servidores para la misma para varios países disponibles aca @NETCOLVIPHC o en las siguientes opciones.\n• Importar el servidor a usar.\n• Ingrese el usuario y clave generado.\n• Y conecte la app..\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n    Inconvenientes al conectar el usuario y demás problemas soporte @NETCOLVIP .\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n   ⚠️ SIGUE EXACTAMENTE LO QUE DICE\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n  😍 ¿TE GUSTA EL SERVICIO? ESCRIBA O HAGA CLIC EN /PIX" \
    --parse_mode html
    return 0
    
}
    
#enviar sks
enviarsks() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ ENVIANDO ARCHIVOS SKS..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/CLARO.sks" \
    return 0
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/VIVO.sks" \
    return 0
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/TIM.sks" \
    return 0
    
}
    
#enviar hc
enviarhc() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ ENVIANDO ARCHIVOS HC..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/CLAROWAZEV1.hc" \
    return 0
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/CLAROWAZEV2.hc" \
    return 0
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/MOVISTARWHATSAPP.hc" \
    return 0


    }

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '♻️ GERAR TESTE ♻️' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text '🔰 DESCARGAR APLICACION 🔰' --callback_data 'appenviar'
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '🔰 ARQUIVOS HC 🔰' --callback_data 'hcenviar'
ShellBot.InlineKeyboardButton --button 'botao1' --line 4 --text '👨‍💻COMPRE AQUI👨‍💻'  --callback_data '2' --url 't.me/NETCOLVIP' # privado
ShellBot.InlineKeyboardButton --button 'botao1' --line 5 --text '⚠️ SOPORTE ⚠️'  --callback_data '3' --url 't.me/NETCOLVIP' # termos
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function enviarapp --callback_data appenviar
ShellBot.regHandleFunction --function enviarsks --callback_data sksenviar
ShellBot.regHandleFunction --function enviarhc --callback_data hcenviar
unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
while :; do
   [[ "$(date +%d)" != "$(cat RESET)" ]] && {
   	echo $(date +%d) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 24
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/PIX"  ]] && pix
    ) &
  done
done
